apiVersion: v1
kind: Pod
metadata:
  name: awscli
  namespace: default
spec:
  containers:
  - name: awscli
    image: amazon/aws-cli:latest 
    command: [ "sleep", "infinity" ]
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: AWS_SECRET_ACCESS_KEY
    - name: AWS_DEFAULT_REGION
      value: us-east-1 # Replace with your desired region
  imagePullSecrets:
  - name: regcred-common-dockerhub
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: default
type: Opaque
data:
  AWS_ACCESS_KEY_ID: XXXXXXXX # Base64-encoded "ABCDEFG"
  AWS_SECRET_ACCESS_KEY: XXXXXXX # Base64-encoded "123456" 
