apiVersion: v1
kind: Pod
metadata:
  labels:
    eks.amazonaws.com/fargate-profile: alb-sample-app
    eks.amazonaws.com/compute-type: fargate
    run: app-demo
  name: app-demo
  namespace: app
spec:
  containers:
  - image: 542760990845.dkr.ecr.us-east-1.amazonaws.com/demo:latest
    imagePullPolicy: Always
    name: app-demo
    ports:
    - containerPort: 5000
    resources: {}
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-pbccn
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: fargate-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-pbccn
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace

#Create Service
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    eks.amazonaws.com/compute-type: fargate
    eks.amazonaws.com/fargate-profile: alb-sample-app
    run: app-demo
  name: app-demo
  namespace: app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  type: NodePort
  selector:
    eks.amazonaws.com/compute-type: fargate
    eks.amazonaws.com/fargate-profile: alb-sample-app
    run: app-demo

#Create INgress
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    eks.amazonaws.com/compute-type: fargate
    eks.amazonaws.com/fargate-profile: alb-sample-app
    run: app-demo
  name: app-demo
  namespace: app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  type: NodePort
  selector:
    eks.amazonaws.com/compute-type: fargate
    eks.amazonaws.com/fargate-profile: alb-sample-app
    run: app-demo
